version: '3.8'

services:
  db:
    image: mysql:8
    container_name: upfinder_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upfinder
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: upfinder_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db